"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {"includes": "pyautogui",
           'argv_emulation': False,
           'packages': ['pyautogui'],
           'iconfile': 'mouse_icon.icns'}

setup(
    app=APP,
    name='Moving Mouse',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
